ktor:
  application:
    modules:
      - com.upet.ApplicationKt.module
  deployment:
    port: ${?PORT}
    host: 0.0.0.0

jwt:
  domain: "https://upet-api.cnvx.com/"
  audience: "upet-clients"
  realm: "upet-app"

database:
  url: ${?DATABASE_URL}
  user: ${?DATABASE_USER}
  password: ${?DATABASE_PASSWORD}

upet:
  routes:
    provider: ${?UPET_ROUTES_PROVIDER} # "dummy" o "google"
  googleMaps:
    apiKey: ${?UPET_GOOGLE_MAPS_API_KEY}