ktor:
  application:
    modules:
      - com.upet.ApplicationKt.module
  deployment:
    port: ${?PORT}
    host: 0.0.0.0

jwt:
  domain: "https://upet-api.cnvx.com/"
  audience: "upet-clients"
  realm: "upet-app"

database:
  url: "jdbc:postgresql://dpg-d4qhiafdiees739ap4v0-a.oregon-postgres.render.com:5432/upet_db_z54t?sslmode=require"
  user: "convex"
  password: "bou9UIJDDLTGUq6zvfre3JsobjYDEljp"